<a href="https://colab.research.google.com/github/Angorith/acorn_python/blob/main/0526_15%EC%9D%BC%EC%B0%A8_Series%EB%8B%A4%EB%A3%A8%EA%B8%B0%2Cpandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
__all__

In [ ]:
from utills import *

*__init__.py*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.index   #like range

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])
obj2
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2['a']

-5

[] : 데이터 접근시 사용
() : 기능
{} : 

In [ ]:
obj2[obj2 >0]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 *2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
obj2['a']
obj2['d']=6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2[obj2> 0]
obj2 *2
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
'b' in obj2

True

In [ ]:
for i in dict_data:
    print(i)

NameError: ignored

In [ ]:
'b' in obj2
'e' in obj2

False

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah' : 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
type(sdata)

dict

In [ ]:
for i in sdata:
    print(i)

Ohio
Texas
Oregon
Utah


In [ ]:
'Ohio' in obj3

True

In [ ]:
for i in obj3:
    print(i)

35000
71000
16000
5000


In [ ]:
states = ['Califonia','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index=states)
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [ ]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [ ]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year' :[2000,2001,2002,2001,2002,2003],
        'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [ ]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [ ]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [ ]:
obj4.isnull()

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [ ]:
obj3+obj4

Califonia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

In [ ]:
frame.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [ ]:
frame.tail(3)

state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                      index= ['one','two','three','four', 'five','six'])

In [ ]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
type(frame2)

pandas.core.frame.DataFrame

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2['state']#칼럼

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.year#칼럼

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
frame2['debt']=16.5

In [ ]:
frame2

year   state  pop  debt   deb
one    2000    Ohio  1.5  16.5  16.5
two    2001    Ohio  1.7  16.5  16.5
three  2002    Ohio  3.6  16.5  16.5
four   2001  Nevada  2.4  16.5  16.5
five   2002  Nevada  2.9  16.5  16.5
six    2003  Nevada  3.2  16.5  16.5

In [ ]:
frame2['debt'] = np.arange(6.)

In [ ]:
range(6)

range(0, 6)

In [ ]:
a= np.arange(6.)

In [ ]:
a

array([0., 1., 2., 3., 4., 5.])

In [ ]:
frame2

year   state  pop  debt   deb
one    2000    Ohio  1.5   0.0  16.5
two    2001    Ohio  1.7   1.0  16.5
three  2002    Ohio  3.6   2.0  16.5
four   2001  Nevada  2.4   3.0  16.5
five   2002  Nevada  2.9   4.0  16.5
six    2003  Nevada  3.2   5.0  16.5

In [ ]:
val = pd.Series([-1.2,-1.5,-1.7], index = ['two','four','five'])

In [ ]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [ ]:
type(val)

pandas.core.series.Series

In [ ]:
frame2['debt']=val

In [ ]:
frame2

year   state  pop  debt   deb
one    2000    Ohio  1.5   NaN  16.5
two    2001    Ohio  1.7  -1.2  16.5
three  2002    Ohio  3.6   NaN  16.5
four   2001  Nevada  2.4  -1.5  16.5
five   2002  Nevada  2.9  -1.7  16.5
six    2003  Nevada  3.2   NaN  16.5

In [ ]:
frame2['eastern']= frame2.state =='Ohio'

In [ ]:
frame2

year   state  pop  debt   deb  eastern
one    2000    Ohio  1.5   NaN  16.5     True
two    2001    Ohio  1.7  -1.2  16.5     True
three  2002    Ohio  3.6   NaN  16.5     True
four   2001  Nevada  2.4  -1.5  16.5    False
five   2002  Nevada  2.9  -1.7  16.5    False
six    2003  Nevada  3.2   NaN  16.5    False

In [ ]:
del frame2['deb']

In [ ]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001:1.7 ,2002: 3.6}}

In [ ]:
frame3 = pd.DataFrame(pop)

In [ ]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [ ]:
pd.DataFrame(pop, index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [ ]:
frame3['Ohio']

2001    1.7
2002    3.6
2000    1.5
Name: Ohio, dtype: float64

In [ ]:
frame3['Ohio'][:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2] }
pd.DataFrame(pdata)

Ohio  Nevada
year              
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
frame3.index.name = 'year'

In [ ]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.columns.name = 'state'

In [ ]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [ ]:
obj = pd.Series(range(3), index = ['a','b','c'])

In [ ]:
obj

a    0
b    1
c    2
dtype: int64

In [ ]:
index = obj.index

In [ ]:
index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1:]   #슬라이싱 가능

Index(['b', 'c'], dtype='object')

In [ ]:
type(index)

pandas.core.indexes.base.Index

In [ ]:
index[1]

'b'

In [ ]:
index[1]='d'        #변경은 불가능

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [ ]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

In [ ]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [ ]:
'Ohio' in frame3.columns

True

In [ ]:
2003 in frame3

False

In [ ]:
2003 in frame3.index

False

In [ ]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [ ]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index =['d','b','a','c'])

In [ ]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [ ]:
obj2 = obj.reindex(['a','b','c','d'])#고치기

In [ ]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [ ]:
obj3 = pd.Series(['blue','purple','yellow'],index = [0,2,4])

In [ ]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(6), method='ffill')#f(front)는 앞의 값 땡겨오기 fill 은 채우라

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index = ['a','c','d'],
                     columns = ['Ohio','Texas','Califonia'])

In [ ]:
frame

Ohio  Texas  Califonia
a     0      1          2
c     3      4          5
d     6      7          8

In [ ]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a= np.arange(9)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.shape

(9,)

In [ ]:
b = a.reshape(3,3)

In [ ]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b.shape

(3, 3)

In [ ]:
frame

Ohio  Texas  Califonia
a     0      1          2
c     3      4          5
d     6      7          8

In [ ]:
frame2 = frame.reindex(['a','b','c','d'])   #row방향 열방향

In [ ]:
frame2

Ohio  Texas  Califonia
a   0.0    1.0        2.0
b   NaN    NaN        NaN
c   3.0    4.0        5.0
d   6.0    7.0        8.0

In [ ]:
states = ['Texas','Utah','Califonia']

In [ ]:
frame.reindex(columns=states)   #column방향 행 방향

Texas  Utah  Califonia
a      1   NaN          2
c      4   NaN          5
d      7   NaN          8

In [ ]:
frame

Ohio  Texas  Califonia
a     0      1          2
c     3      4          5
d     6      7          8

In [ ]:
frame.loc[['a','c','d'],:]

Ohio  Texas  Califonia
a     0      1          2
c     3      4          5
d     6      7          8

In [ ]:
data=pd.DataFrame(np.arange(8*2).reshape((4, 4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop('two',axis =1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [ ]:
obj.drop('c',inplace = True)

------------

In [ ]:
obj

d    4.5
b    7.2
a   -5.3
dtype: float64

In [ ]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])

In [ ]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
obj['b']

1.0

In [ ]:
obj[1]  #Series 의 index는 'a, b,c,d'인데 기본내부적인 index의 번호도 가지고있다.

1.0

In [ ]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [ ]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [ ]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [ ]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [ ]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [ ]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index = ['Ohio','Colorado','Utah','New York'],
                    columns = ['one','two','three','four'])

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(16).shape

(16,)

In [ ]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.arange(16).reshape((4,4)).shape

(4, 4)

In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [ ]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [ ]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[data<5]=0

In [ ]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc['Colorado',['two','three']]# [index(row)[column]]

two      5
three    6
Name: Colorado, dtype: int64

In [ ]:
data.iloc[2, 1] #숫자 표시 [row, column]

9

In [ ]:
data.iloc[2,1]

In [ ]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [ ]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [ ]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [ ]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [ ]:
ser = pd.Series(np.arange(3,))

In [ ]:
ser

0    0
1    1
2    2
dtype: int64

In [ ]:
ser[-1;]

KeyError: ignored

In [ ]:
ser[:1]

0    0
dtype: int64

In [ ]:
ser.loc[:1]

0    0
1    1
dtype: int64

In [ ]:
ser.iloc[:1]

0    0
dtype: int64

--------------------

In [ ]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2 = pd.Series([-2.1,3.6, -1.5,4,3.1], index=['a','c','e','f','g'])

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9,).reshape((3,3)),columns=list('bcd'),
                   index = ['Ohio','Texas','Colorado'])

In [ ]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [ ]:
list('bcd')

['b', 'c', 'd']

In [ ]:
np.arange(9.0).reshape((3,3)).shape

(3, 3)

In [ ]:
df2 = pd.DataFrame(np.arange(12,).reshape((4, 3)), columns = list('bde'),
                   index= ['Utah','Ohio','Texas','Oregon'])

In [ ]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
np.arange(12,).reshape((4,3)).shape #2차원

(4, 3)

In [ ]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [ ]:
df1 = pd.DataFrame({'A':[1,2]})

In [ ]:
df1

A
0  1
1  2

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns = list('abcd'))

In [ ]:
list('abcd')

['a', 'b', 'c', 'd']

In [ ]:
np.arange(12.).reshape((3,4))

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns=list('abcde'))

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
np.arange(20.).reshape((2,-1)).shape    #-1 20개중 5로 나눈걸 너가 알아서 채워넣어 (magic keyword)

(2, 10)

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value=0)  #df1 에 없는 값을 df2에서 가져와 df2의값과 fill_value=0과 합해서 출력

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.loc[1,'b']=np.nan

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
arr = np.arange(12.).reshape((3,4))

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.arange(12.).reshape((3,4)).shape

(3, 4)

In [ ]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr[0]

array([0., 1., 2., 3.])

In [ ]:
arr-arr[0]  #dataFrame에서 row를 뺐음

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns = list('bde'),
                     index = ['Utah','Ohio','Texas','Oregon'])

In [ ]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
list('bde')

['b', 'd', 'e']

In [ ]:
np.arange(12.).reshape((4,3))

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series = frame.iloc[0]

In [ ]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [ ]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
series2 = pd.Series(range(3), index=['b','e','f'])

In [ ]:
series2

b    0
e    1
f    2
dtype: int64

In [ ]:
frame +series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

---------------------

In [ ]:
series3 = frame['d']

In [ ]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [ ]:
frame.sub(series3 , axis='index')   # frame['d']의 값을 뺐음

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [ ]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),  #random 결측값 입력됨
                    index=['Utah','Ohio','Texas','Oregon'])

In [ ]:
frame

b         d         e
Utah   -1.241210 -0.043590 -0.749811
Ohio   -0.866328  0.903727  0.166917
Texas   1.064861 -0.528608 -0.648747
Oregon -1.352537 -0.385706  0.314451

In [ ]:
np.random.rand(4,3) # 0~1 까지 정규 분포

array([[0.67710755, 0.00819499, 0.48704865],
       [0.46776285, 0.29652198, 0.7512553 ],
       [0.73514362, 0.25653849, 0.13074522],
       [0.29056403, 0.03757727, 0.83393293]])

In [ ]:
np.random.randn(4,3)

array([[ 1.50271869,  0.20602865, -0.65326416],
       [-0.27410191, -1.99866746, -0.17069361],
       [-0.29316048,  1.18643485, -0.92767223],
       [-0.9830107 , -0.34391376,  0.18279174]])

In [ ]:
np.abs(frame)   #abs는 절대값을 계산해주는 함수

b         d         e
Utah    1.241210  0.043590  0.749811
Ohio    0.866328  0.903727  0.166917
Texas   1.064861  0.528608  0.648747
Oregon  1.352537  0.385706  0.314451

In [ ]:
f = lambda x:x.max() - x.min()  #frame 에서 x.max()값을 불러와 x.min()을 뺸것
frame.apply(f)

b    2.417398
d    1.432335
e    1.064262
dtype: float64

In [ ]:
1.064861 - (-1.352537)

2.4173980000000004

lambda 변수가 함수에 들어가는 느낌

간단하게 뭔갈 쓰고 싶을 때 쓰는것

In [ ]:
x = lambda a: a+8

In [ ]:
x(2)    #x(a) = a: a+8

10

In [ ]:
(lambda a:a+8)(2)

10

In [ ]:
x = lambda a,b,c:a+b+c

In [ ]:
x(1,2,3)

6

In [ ]:
def myfunc(n):
    return lambda a: a*n

In [ ]:
doubler = myfunc(2) #2 는 n , doubler = lambda a: a*(n)2

In [ ]:
doubler

<function __main__.myfunc.<locals>.<lambda>>

In [ ]:
doubler(11)

22

In [ ]:
map

map

In [ ]:
format = lambda x : '%.2f'% x

In [ ]:
frame['e']

Utah     -0.749811
Ohio      0.166917
Texas    -0.648747
Oregon    0.314451
Name: e, dtype: float64

In [ ]:
frame['e'].map(format)

Utah      -0.75
Ohio       0.17
Texas     -0.65
Oregon     0.31
Name: e, dtype: object

In [ ]:
obj = pd.Series(range(4), index=['d','a','b','c'])

In [ ]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index = ['three','one'],
                     columns = ['d','a','b','c'])

In [ ]:
np.arange(8).reshape((-1,4)).shape

(2, 4)

In [ ]:
np.arange(8).reshape((-1, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [ ]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
frame.sort_index(axis=1)    #칼럼방향 올림차순

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [ ]:
frame.sort_index(axis=1, ascending=False )#칼럼방향 내림차순

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [ ]:
obj = pd.Series([4,7,-3,2])

In [ ]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [ ]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [ ]:
obj = pd.Series([4,np.nan,7,np.nan, -3, 2])

In [ ]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [ ]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [ ]:
frame = pd.DataFrame({'b':[4,7,-3,2], 'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [ ]:
frame.sort_values(by='a')   #a 캄럼 오름차순

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [ ]:
frame.sort_values(by=['a','b'])   #a와 b 캄럼 오름차순

b  a
2 -3  0
0  4  0
3  2  1
1  7  1